name: End-to-end testing Researcher

on:
  pull_request:
    branches: ["main"]
    paths:
      - "package.json"
      - "apps/researcher/**"
      - ".github/workflows/end-to-end-testing-researcher.yml"
      - "packages/**"

jobs:
  run-end-to-end-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Wait for a successful Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: waitForPreview
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 600
          environment: Preview – colonial-collections-researcher
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Cypress for Researcher 🌲
        uses: cypress-io/github-action@v6
        with:
          project: ./apps/researcher
          wait-on: ${{ steps.waitForPreview.outputs.url }}
        env:
          CYPRESS_BASE_URL: ${{ steps.waitForPreview.outputs.url }}
