name: End-to-end testing Dataset Browser

on:
  pull_request:
    branches: ['main']
    paths:
      - 'package.json'
      - 'apps/dataset-browser/**'
      - '.github/workflows/end-to-end-testing-dataset-browser.yml'
      - 'packages/**'

jobs:
  run-end-to-end-tests:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Wait for a successful Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.2
        id: waitForVercelPreviewDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 600
          environment: Preview – colonial-collections-dataset-browser
      - name: Run Playwright tests
        run: npm run test:e2e -w dataset-browser
        env:
          PLAYWRIGHT_BASE_URL: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: dataset-browser-playwright-report
          path: apps/dataset-browser/playwright-report/
          retention-days: 30
