name: End-to-end testing Dataset Browser
on:
  pull_request:
    branches: ["main"]
    paths:
      - 'package.json'
      - 'apps/dataset-browser/**'
      - .github/workflows/end-to-end-testing-dataset-browser.yml
jobs:
  run-end-to-end-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Waiting for 200 from the Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: waitFor200
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 60
          environment: Preview – colonial-collections-dataset-browser
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Cypress for Dataset Browser 🌲
        uses: cypress-io/github-action@v5
        with:
          project: ./apps/dataset-browser
          wait-on: ${{ steps.waitFor200.outputs.url }}
        env:
          CYPRESS_BASE_URL: ${{ steps.waitFor200.outputs.url }}