name: End-to-end testing Dataset Browser

on:
  pull_request:
    branches: ["main"]
    paths:
      - "package.json"
      - "apps/dataset-browser/**"
      - ".github/workflows/end-to-end-testing-dataset-browser.yml"
      - "packages/**"

jobs:
  test_setup:
    name: Test setup
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
    steps:
      - name: Wait for a successful Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: waitForVercelPreviewDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 600
  run-end-to-end-tests:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        working-directory: apps/dataset-browser
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        working-directory: apps/dataset-browser
        run: npx playwright test
        env:
          PLAYWRIGHT_BASE_URL: ${{ needs.test_setup.outputs.preview_url }}
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: dataset-browser-playwright-report
          path: apps/dataset-browser/playwright-report/
          retention-days: 30