name: End-to-end testing Dataset Browser

on:
  pull_request:
    branches: ["main"]
    paths:
      - "package.json"
      - "apps/dataset-browser/**"
      - ".github/workflows/end-to-end-testing-dataset-browser.yml"
      - "packages/**"

jobs:
  run-end-to-end-tests:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/playwright:v1.43.0-jammy
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Wait for a successful Vercel Preview
      uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
      id: waitForVercelPreviewDeployment
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        max_timeout: 600
        environment: Preview – colonial-collections-dataset-browser
    - name: Run Playwright tests
      run: npm run test:e2e -w dataset-browser
      env:
        HOME: /root
        PLAYWRIGHT_BASE_URL: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: dataset-browser-playwright-report
        path: apps/dataset-browser/playwright-report/
        retention-days: 30