name: End-to-end testing Researcher

on:
  pull_request:
    branches: ["main"]
    paths:
      - "package.json"
      - "apps/researcher/**"
      - ".github/workflows/end-to-end-testing-researcher.yml"
      - "packages/**"

jobs:
  run-end-to-end-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Wait for a successful Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: waitForPreview
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 600
          environment: Preview – colonial-collections-researcher
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Cypress for Researcher 🌲
        uses: cypress-io/github-action@v6
        with:
          project: ./apps/researcher
          wait-on: ${{ steps.waitForPreview.outputs.url }}
        env:
          # Used in the Cypress tests
          CYPRESS_BASE_URL: ${{ steps.waitForPreview.outputs.url }}
          CYPRESS_TEST_USER_EMAIL: ${{secrets.TEST_USER_EMAIL}}
          CYPRESS_TEST_USER_PASSWORD: ${{secrets.TEST_USER_PASSWORD}}
          CYPRESS_TEST_COMMUNITY_SLUG: ${{secrets.TEST_COMMUNITY_SLUG}}
          # Used in the Cypress tasks
          TEST_USER_ID: ${{secrets.TEST_USER_ID}}
          TEST_COMMUNITY_ID: ${{secrets.TEST_COMMUNITY_ID}}
          DATABASE_URL: ${{secrets.TEST_DATABASE_URL}}
          SPARQL_ENDPOINT_URL: ${{secrets.SPARQL_ENDPOINT_URL}}
          SEARCH_ENDPOINT_URL: ${{secrets.SEARCH_ENDPOINT_URL}}
      # Screenshots will be generated only if the test failed
      # thus we store screenshots only on failures
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: ./apps/researcher/cypress/screenshots
      # Test run video is always captured, so this action uses "always()" condition
      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: ./apps/researcher/cypress/videos